name: Deploy to Heroku

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/docker-login@v1
      with:
        login-server: ccr.ccs.tencentyun.com
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: build and push
      run: |
        docker build . -t ccr.ccs.tencentyun.com/${{ secrets.NAMESPACE }}/team_work_backend:${{ github.sha }}
        docker push ccr.ccs.tencentyun.com/${{ secrets.NAMESPACE }}/team_work_backend:${{ github.sha }}